language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git config --local user.name impulso-io;
  fi
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git config --local user.email talkto.impulso.io@gmail.com;
  fi
script:
- sbt test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- '[ $TRAVIS_PULL_REQUEST = "false" ] && sh "$TRAVIS_BUILD_DIR/bintray.sh" && sbt
  "release with-defaults"'
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
env:
  global:
  - secure: fDrZVpFstLj55whQaRAQ93LnEfVoKZTHcNt5PjSNIL11yfU5H6Ku4DAf52pzkmZZ3v6S5j4B6Wl574wvYJVID0EuGpTaSRe+V1D/noJBdCQvjG7QazLP/9enH8dkUSFczd4SF1YCfCucPpHPZafiFlR4c63/JHvUaeWCt6nxPNCBpetL3jCHTy2Bpb7iN/qQwIubPh5ct+ZbgkMZvDX1yK0h3XAPfcqNWQTNUqo2+2ivkzOlMJE2r3p1s+OMU4juDihOC6OQRMMzjqg/7eKj30CUJf+1PkSILZmOJh5uS2orT0O9t2SWjWwhzfbiN9KkcjWT53c3f5uowu8GEVJQdbCc14nSUlq3eVOMLqj2dkplu7awmXX+WLnLb6nba3RwOUFUVm2LHVHQ/rhMPFDT6ubjqFBWkPZ/gjFJWcgfM26QL7zdkj4S7QZvYo3r6aUlYU79sWTDRQh2+wOAYRQLYmTDDaHKCgbAc5LS/ndHw5YHMLP24SdiHvzua6csaog6YWbCkFH9ase15Qz+Olm+FNfJKzTkJM3Crvf2+l79w2SGC2o4FPbzXrqP3Y8IC0WWN2wdd7NDHhOuQ5Zhu/oU5MjlW1SLktGLxqpoNSSaT4FXFwiTI1KEr2a6dTme5hhZqyCM/ej1ye2oyV4tavgzaZfUEu1SIN+RMbwSXERwHvc=
  - secure: kvj3b8hFpcaJI+ZIFJ/NWZldZrMXGGh0K1qAliFjj1fq3hfB+x1h3CwTvcrL6Pa6yS8j2m2RZd0UQBWK5WUh6viaUBBgmJHelrib7rgjhwIaGqVTLQ4nKmVT+1Z//hSfD0xCs+HSd2acmwQyZAeZ0TQ2wI1YZp+iM6uJpFgDa4eZ4t7y1qGusjbJtdvsNhQiMuhJlHCItEvQ7YYyVPus4d4xx3O2743BKYKtdImXmZU+RyOmHrn01rhh9L8f7uFR5YYKtgout2o5FPzDRKtlsAElCkOAjL4RAgat3fkpd5kJj92zoTDePg97zr4cM9FBf89Sku7NNe6A5bYVjB9/OVFIllnJvMohR73R3fCffafsiDFdG+A9vbghWAQL2aHMzG1MqndbFcLu9MeFf2cOR5JRB8EV7X7XbkzzRhDMJB7XhoLqMwv4k8wL1Entovrw/my06l65SAeBtHo3+XZjBIiIbK+ZDzfsR1sqaWA/VaRgn07SVawaIRuBJeKPr/gCM5PEinyrgMqAwnrKOUlw4eP3xIlMThlur6ysbPR+bI8VCiaEgw8BZ+E1YLaktsiteyoRRM9UJkJIV0YWx2LK+autQGRFoPvEWB3mmNXQg84B0odtkw28Q5TCjHMiYQFWOQ3Sh1x88/esa5V/LkkJ9+qCYdHVSZCbSFGaidfK6Ms=
